import { vi } from 'vitest';
import type { ImapService } from '../../src/services/imap/imap.service';
import { loadJsonFixture } from './helpers';

/**
 * Creates a mock IMAP service for testing
 */
export function createMockImapService() {
  return {
    connect: vi.fn().mockResolvedValue(undefined),
    disconnect: vi.fn().mockResolvedValue(undefined),
    searchNewsletters: vi.fn(),
    markAsRead: vi.fn().mockResolvedValue(undefined),
    deleteEmail: vi.fn().mockResolvedValue(undefined),
  } as unknown as ImapService;
}

/**
 * Sets up the mock IMAP service to return sample emails
 */
export async function setupMockImapWithFixtures(mockImap: any) {
  const sampleEmails = await loadJsonFixture('sample-emails.json');

  mockImap.searchNewsletters.mockResolvedValue(
    sampleEmails.map((email: any) => ({
      uid: email.uid,
      subject: email.subject,
      from: email.from,
      date: new Date(email.date),
      html: email.html,
      text: email.text,
    }))
  );

  return mockImap;
}

/**
 * Creates a mock scraper function that returns fixture data
 */
export async function createMockScraper() {
  const sampleArticles = await loadJsonFixture('sample-articles.json');

  return vi.fn((url: string) => {
    const article = sampleArticles[url as keyof typeof sampleArticles];
    if (!article) {
      return Promise.resolve({
        url,
        title: 'Unknown Article',
        content: 'Content not found',
      });
    }

    return Promise.resolve({
      url,
      title: article.title,
      content: article.content,
      author: article.author,
      published: article.publishDate,
    });
  });
}

/**
 * Creates a mock LLM service that returns formatted summaries
 */
export function createMockLLM() {
  return vi.fn((prompt: string) => {
    // Simple mock that returns a structured response
    const mockSummary = {
      summaries: [
        {
          title: 'Test Article',
          summary: 'This is a test summary generated by the mock LLM.',
          tags: ['testing', 'mocking'],
          url: 'https://example.com/test',
        },
      ],
    };

    return Promise.resolve({
      text: JSON.stringify(mockSummary),
      usage: { promptTokens: 100, completionTokens: 50, totalTokens: 150 },
    });
  });
}

/**
 * Creates a more realistic mock LLM that generates summaries based on input
 */
export function createSmartMockLLM() {
  return vi.fn((prompt: string, articles: any[]) => {
    const summaries = articles.map((article, index) => ({
      title: article.title || `Article ${index + 1}`,
      summary: article.content
        ? `Summary: ${article.content.substring(0, 100)}...`
        : 'No content available for summary.',
      tags: ['test', 'mock'],
      url: article.url,
    }));

    return Promise.resolve({
      text: JSON.stringify({ summaries }),
      usage: {
        promptTokens: articles.length * 50,
        completionTokens: summaries.length * 30,
        totalTokens: articles.length * 50 + summaries.length * 30,
      },
    });
  });
}

/**
 * Mock fetch for URL title extraction
 */
export function createMockFetch() {
  return vi.fn((url: string) => {
    return Promise.resolve({
      ok: true,
      status: 200,
      text: () => Promise.resolve(`<html><head><title>Title for ${url}</title></head><body>Content</body></html>`),
    });
  });
}

/**
 * Mocks the article extractor to return titles
 */
export async function mockArticleExtractor() {
  const sampleArticles = await loadJsonFixture('sample-articles.json');

  return {
    extract: vi.fn((url: string) => {
      const article = sampleArticles[url as keyof typeof sampleArticles];
      if (!article) {
        return Promise.resolve({ title: 'Unknown Title' });
      }
      return Promise.resolve({ title: article.title });
    }),
  };
}
